import Sidebar from "@/components/sidebar/Sidebar";
import CartAddProver from "@/provider/CartAddProver";

export const metadata = {
    title: "Store - Buy or Rent Books",
    description: "Generated by create next app",
};

export default function BookStoreLayout({ children }) {
    return (

        <div className="h-screen bg-gray-300">
            <div className="grid grid-cols-1 sm:grid-cols-[160px_1fr] gap-4 p-3">
                <CartAddProver>
                    <Sidebar />
                    {children}
                </CartAddProver>
            </div>
        </div>
    );
}
