import Sidebar from "@/components/sidebar/Sidebar";

export const metadata = {
    title: "Store - Buy or Rent Books",
    description: "Generated by create next app",
};

export default function BookStoreLayout({ children }) {
    return (

        <div className="h-screen bg-gray-300">
            <div className="grid grid-cols-1 sm:grid-cols-[160px_1fr] gap-8 p-3">
                <Sidebar/>
                {children}
            </div>
        </div>
    );
}
